spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    topic: "library-events"
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer